# Generated by Django 5.2.4 on 2025-11-17 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0004_completedorder_alter_order_cdek_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'Создан'), ('AUTHORIZED', 'Ожидает подтверждения'), ('CONFIRMED', 'Оплачено'), ('PARTIAL_REVERSED', 'Частично отменена'), ('REVERSED', 'Отменена после холдирования'), ('CANCELED', 'Отменена по ссылке'), ('PARTIAL_REFUNDED', 'Частичный возврат'), ('REFUNDED', 'Полный возврат'), ('REJECTED', 'Ошибка списания'), ('DEADLINE_EXPIRED', 'Истек срок ожидания 3DS')], default='NEW', max_length=32)),
                ('amount', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('denomination', models.IntegerField()),
                ('type', models.CharField(choices=[('DIGITAL', 'цифровой'), ('PHYSICAL', 'физический')], default='DIGITAL', max_length=32)),
                ('promo', models.CharField(max_length=40, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='order.order')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
