# Generated by Django 5.2.4 on 2025-11-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('NEW', 'Создан'), ('AUTHORIZED', 'Ожидает подтверждения'), ('CONFIRMED', 'Оплачено'), ('PARTIAL_REVERSED', 'Частично отменена'), ('REVERSED', 'Отменена после холдирования'), ('CANCELED', 'Отменена по ссылке'), ('PARTIAL_REFUNDED', 'Частичный возврат'), ('REFUNDED', 'Полный возврат'), ('REJECTED', 'Ошибка списания'), ('DEADLINE_EXPIRED', 'Истек срок ожидания 3DS')], default='NEW', max_length=32)),
                ('amount', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField()),
                ('promo', models.CharField(max_length=40, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_sold', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
