# Generated by Django 5.2.4 on 2025-07-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('N', 'NEW'), ('A', 'AUTHORIZED'), ('C', 'CONFIRMED'), ('R', 'REJECTED')], default='N', max_length=1),
        ),
    ]
