# Generated by Django 5.2.4 on 2025-11-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='is_sold',
        ),
    ]
