# Generated by Django 5.2.4 on 2025-11-17 08:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_completedorder_alter_order_cdek_and_more'),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='order.order'),
        ),
        migrations.AddField(
            model_name='promocode',
            name='type',
            field=models.CharField(choices=[('DIGITAL', 'цифровой'), ('PHYSICAL', 'физический')], default='DIGITAL', max_length=32),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
