# Generated by Django 5.2.4 on 2025-11-17 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_promocode_order_promocode_type_alter_promocode_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='id_new',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
