# Generated by Django 5.2.4 on 2025-08-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_alter_payment_options_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('NEW', 'Создан'), ('AUTHORIZED', 'Ожидает подтверждения'), ('CONFIRMED', 'Оплачено'), ('PARTIAL_REVERSED', 'Частично отменена'), ('REVERSED', 'Отменена после холдирования'), ('CANCELED', 'Отменена по ссылке'), ('PARTIAL_REFUNDED', 'Частичный возврат'), ('REFUNDED', 'Полный возврат'), ('REJECTED', 'Ошибка списания'), ('DEADLINE_EXPIRED', 'Истек срок ожидания 3DS')], default='NEW', max_length=32),
        ),
    ]
