# Generated by Django 5.2.4 on 2025-11-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_promocode_order_promocode_type_alter_promocode_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='id',
            new_name='id_new',
        ),
    ]
