# Generated by Django 5.2.4 on 2025-10-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_payment_updated_at_alter_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominaion', models.IntegerField()),
                ('code', models.CharField(max_length=30)),
                ('promo', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
