# Generated by Django 5.2.4 on 2025-10-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0004_promocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='denominaion',
            new_name='denomination',
        ),
    ]
