# Generated by Django 5.2.4 on 2025-10-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_rename_denominaion_promocode_denomination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocode',
            name='code',
        ),
        migrations.AddField(
            model_name='promocode',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='promocode',
            name='promo',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
