# Generated by Django 5.2.4 on 2025-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_squashed_0006_remove_promocode_code_promocode_is_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
