# Generated by Django 5.2.4 on 2025-11-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CdekOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('user_fullname', models.CharField(max_length=200)),
                ('tariff_code', models.IntegerField()),
                ('city_code', models.IntegerField(default=None, null=True)),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
