# Generated by Django 5.2.4 on 2025-11-17 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cdek', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdekorder',
            options={'verbose_name': 'Заказ в СДЭК', 'verbose_name_plural': 'Заказы в СДЭК'},
        ),
    ]
