# Generated by Django 5.2.4 on 2025-11-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdek', '0002_alter_cdekorder_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdekorder',
            name='pvz_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cdekorder',
            name='city_code',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
