# Generated by Django 5.2.4 on 2025-07-23 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filehandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
    ]
