# Generated by Django 5.2.4 on 2025-11-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehandler', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='format',
            field=models.CharField(default='mp4', max_length=20),
        ),
    ]
