# Generated by Django 5.2.4 on 2025-08-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filehandler', '0002_alter_file_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
