# Generated by Django 5.2.4 on 2025-11-09 20:04

import django.db.models.deletion
import order.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filehandler', '0001_initial'),
        ('pay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CdekOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('user_fullname', models.CharField(max_length=200)),
                ('tariff_code', models.IntegerField()),
                ('city_code', models.IntegerField()),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('size', models.IntegerField()),
                ('box_sizes', models.CharField(max_length=20, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('cost', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('technology', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': 'Виды товаров',
            },
        ),
        migrations.CreateModel(
            name='GoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('colorName', models.CharField(max_length=30)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='order.good')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='GoodVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=order.models.timestamp_filename)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.goodvariant')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'Создан'), ('PROCESSING', 'В обработке'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CONFIRMED', 'Завершен'), ('CANCELED', 'Отменен'), ('RETURNED', 'Возврат')], default='NEW', max_length=32)),
                ('phone', models.CharField(default='', max_length=32)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cdek', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='order.cdekorder')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pay.payment')),
                ('promocode', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filehandler.file')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ доставлен',
                'verbose_name_plural': 'Доставленные заказы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Новый заказ',
                'verbose_name_plural': 'Новые заказы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='ProcessingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ в обработке',
                'verbose_name_plural': 'Заказы в обработке',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='ShippedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ в доставке',
                'verbose_name_plural': 'Заказы в доставке',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('good_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.goodvariant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе ',
            },
        ),
    ]
