# Generated by Django 5.2.4 on 2025-11-13 16:30

import django.db.models.deletion
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cdek', '0001_initial'),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('size', models.IntegerField()),
                ('box_sizes', models.CharField(max_length=20, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('technology', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': 'Виды товаров',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе ',
            },
        ),
        migrations.CreateModel(
            name='GoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('colorName', models.CharField(max_length=30)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='order.good')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='GoodVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=order.models.timestamp_filename)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.goodvariant')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'Создан'), ('PROCESSING', 'В обработке'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CONFIRMED', 'Завершен'), ('CANCELED', 'Отменен'), ('RETURNED', 'Возврат')], default='NEW', max_length=32)),
                ('phone', models.CharField(default='', max_length=32)),
                ('comment', models.TextField(default='', max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cdek', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='cdek.cdekorder')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pay.payment')),
                ('promocode', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='pay.promocode')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
