# Generated by Django 5.2.4 on 2025-10-25 19:16

import django.db.models.deletion
import order.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('order', '0001_initial'), ('order', '0002_alter_good_options_alter_goodvariant_options_and_more'), ('order', '0003_alter_order_status'), ('order', '0004_rename_price_goodvariant_cost_good_technology'), ('order', '0005_goodvariantimage_remove_goodvariant_image'), ('order', '0006_order_promocode')]

    initial = True

    dependencies = [
        ('filehandler', '0001_initial'),
        ('pay', '0001_initial'),
        ('pay', '0006_remove_promocode_code_promocode_is_used_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('technology', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Вид товара',
                'verbose_name_plural': 'Виды товаров',
            },
        ),
        migrations.CreateModel(
            name='GoodVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('cost', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='order.good')),
                ('colorName', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('NEW', 'Создан'), ('PROCESSING', 'В обработке'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CONFIRMED', 'Завершен'), ('CANCELED', 'Отменен'), ('RETURNED', 'Возврат')], default='NEW', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pay.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('video', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filehandler.file')),
                ('promocode', models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pay.promocode')),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('good_variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.goodvariant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе ',
            },
        ),
        migrations.CreateModel(
            name='GoodVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=order.models.timestamp_filename)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.goodvariant')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
