# Generated by Django 5.2.4 on 2025-11-17 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pay.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_order', to='pay.promocode'),
        ),
    ]
