# Generated by Django 5.2.4 on 2025-07-21 21:53

import django.db.models.deletion
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='pay.payment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodvariant',
            name='image',
            field=models.ImageField(upload_to=order.models.timestamp_filename),
        ),
        migrations.AlterField(
            model_name='goodvariant',
            name='size',
            field=models.IntegerField(),
        ),
    ]
