# Generated by Django 5.2.4 on 2025-08-04 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_good_options_alter_goodvariant_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Создан'), ('PROCESSING', 'В обработке'), ('SHIPPED', 'Отправлен'), ('DELIVERED', 'Доставлен'), ('CONFIRMED', 'Завершен'), ('CANCELED', 'Отменен'), ('RETURNED', 'Возврат')], default='NEW', max_length=32),
        ),
    ]
