# Generated by Django 5.2.4 on 2025-11-17 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filehandler', '0002_initial'),
        ('order', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='filehandler.file'),
        ),
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Завершенный заказ',
                'verbose_name_plural': 'Завершенные заказы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='DeliveredOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ доставлен',
                'verbose_name_plural': 'Доставленные заказы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='NewOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Новый заказ',
                'verbose_name_plural': 'Новые заказы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='ProcessingOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ в обработке',
                'verbose_name_plural': 'Заказы в обработке',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.CreateModel(
            name='ShippedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Заказ в доставке',
                'verbose_name_plural': 'Заказы в доставке',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='good_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='order.goodvariant'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order'),
        ),
    ]
