# Generated by Django 5.2.4 on 2025-11-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_cdek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdekorder',
            name='city_code',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
