# Generated by Django 5.2.4 on 2025-10-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goodvariant',
            old_name='price',
            new_name='cost',
        ),
        migrations.AddField(
            model_name='good',
            name='technology',
            field=models.JSONField(default=list),
        ),
    ]
