# Generated by Django 5.2.4 on 2025-11-17 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdek', '0001_initial'),
        ('filehandler', '0002_remove_file_name'),
        ('order', '0003_remove_order_phone_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedOrder',
            fields=[
            ],
            options={
                'verbose_name': 'Завершенный заказ',
                'verbose_name_plural': 'Завершенные заказы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('order.order',),
        ),
        migrations.AlterField(
            model_name='order',
            name='cdek',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='cdek.cdekorder'),
        ),
        migrations.AlterField(
            model_name='order',
            name='promocode',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_order', to='pay.promocode'),
        ),
        migrations.AlterField(
            model_name='order',
            name='video',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='filehandler.file'),
        ),
    ]
