# Generated by Django 5.2.4 on 2025-10-28 12:00

import django.db.models.deletion
import order.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_price_goodvariant_cost_good_technology'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodvariant',
            name='colorName',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodvariant',
            name='color',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='goodvariant',
            name='image',
        ),
        migrations.CreateModel(
            name='GoodVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=order.models.timestamp_filename)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='order.goodvariant')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
            },
        ),
    ]
