# Generated by Django 5.2.4 on 2025-10-25 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_squashed_0006_order_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodvariant',
            name='colorName',
            field=models.CharField(max_length=30),
        ),
    ]
