# Generated by Django 5.2.4 on 2025-10-25 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_alter_payment_id'),
        ('order', '0007_alter_goodvariant_colorname'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                """
                -- Drop existing FK constraints if present (names may vary across DBs)
                DO $$
                DECLARE r RECORD;
                BEGIN
                  FOR r IN (
                    SELECT conname FROM pg_constraint
                    WHERE conrelid = 'order_order'::regclass
                      AND contype = 'f'
                      AND conkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid='order_order'::regclass AND attname='payment_id')]
                  ) LOOP
                    EXECUTE format('ALTER TABLE order_order DROP CONSTRAINT %I', r.conname);
                  END LOOP;
                END$$;

                -- Alter column type to bigint
                ALTER TABLE order_order
                  ALTER COLUMN payment_id TYPE bigint USING payment_id::bigint;

                -- Recreate FK constraint
                ALTER TABLE order_order
                  ADD CONSTRAINT order_order_payment_id_fkey
                  FOREIGN KEY (payment_id)
                  REFERENCES pay_payment(id)
                  DEFERRABLE INITIALLY DEFERRED;
                """
            ),
            reverse_sql=(
                """
                DO $$
                DECLARE r RECORD;
                BEGIN
                  FOR r IN (
                    SELECT conname FROM pg_constraint
                    WHERE conrelid = 'order_order'::regclass
                      AND contype = 'f'
                      AND conkey = ARRAY[(SELECT attnum FROM pg_attribute WHERE attrelid='order_order'::regclass AND attname='payment_id')]
                  ) LOOP
                    EXECUTE format('ALTER TABLE order_order DROP CONSTRAINT %I', r.conname);
                  END LOOP;
                END$$;

                ALTER TABLE order_order
                  ALTER COLUMN payment_id TYPE integer USING payment_id::integer;

                ALTER TABLE order_order
                  ADD CONSTRAINT order_order_payment_id_fkey
                  FOREIGN KEY (payment_id)
                  REFERENCES pay_payment(id)
                  DEFERRABLE INITIALLY DEFERRED;
                """
            ),
        )
    ]

