# Generated by Django 5.2.4 on 2025-11-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_payment_fk_to_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=300),
        ),
    ]

