name: Deploy on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH to server and rebuild project
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /projects/3xel-new
            git pull origin
            make npm-install
            make build
            pkill gunicorn
            make migrate
            make gun-start